version: '3.3'

services:
  minion:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../nginx/exp.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 3000:3000
    restart: unless-stopped
